receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}
  resource:
    attributes:
      - key: service.name
        action: upsert
        from_attribute: resource.service.name

exporters:
  debug:
    verbosity: detailed
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "otel-logs"  # Correct date pattern format
    traces_index: "otel-tracers"
    mapping:
      mode: "ecs"
    retry:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
    flush:
      bytes: 1048576  # 1MB
      interval: "10s"
    timeout: "10s"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, elasticsearch]
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, elasticsearch]